### PR TITLE
Fix incorrect app bundle file name detection

### LINKED ISSUE #381: App Bundle upload task doesn't work if project sets archivesBaseName property
### Describe the bug

When project sets `archivesBaseName` to custom value different from `name` property `publishReleaseBundle` task fails.

### To Reproduce

1. Set `archivesBaseNameProperty` to custom value.For example:
```
android {
    defaultConfig {
        versionName "1.0.0"
        archivesBaseName = "$archivesBaseName-$versionName"
    }
}
```
2. Run `./gradlew publishReleaseBundle`
3. Task fails with 
```
A problem was found with the configuration of task ':app:publishReleaseBundle'.
> File '/home/alapshin/workspace/android/foobar/app/build/outputs/bundle/release/app.aab' specified for property 'bundle' does not exist.
```
#### Versions

 - Gradle Play Publisher: 2.0.0-SNAPSHOT
 - Gradle Wrapper (if applicable): 4.9
 - Android Gradle Plugin (if applicable): 3.2.0-beta04

### Expected behavior

Task should correctly detect App Bundle file name and upload it.

### Additional context

Related bug in Google's issuetracker: https://issuetracker.google.com/issues/80552039

### PR DESCRIPTION
**Pull request by alapshin**
Fixes #381

### CODE REVIEW

**Comment by alapshin** [comment]
Sorry, looks like this property is not available on project variable declared in plugin.
However it is  available when running in custom task declared via file. I will have to think of something else.

**Comment by alapshin** [comment]
I had to query this property using its name similar to how Android Gradle plugin does it:
https://android.googlesource.com/platform/tools/base/+/studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/tasks/PackageSplitRes.java#114

If there is a better way to do this please feel free to correct me.

**Comment by alapshin** [comment]
> Will this work if you don't set the base name?

Yes it should work.
By default this property will be equal to `project.name`:
https://docs.gradle.org/current/dsl/org.gradle.api.plugins.BasePluginConvention.html#org.gradle.api.plugins.BasePluginConvention:archivesBaseName

This link is about java plugin but as far as I am aware android plugin follows the same convention.

**Comment by SUPERCILEX** [comment]
Cool beans! Either @bhurling or me will have to check that. (PSA: I'm gone until Monday)

**Comment by SUPERCILEX** [comment]
Oh, I completely forgot about this PR. Sorry! ❤️ Will check later today

**Pull request merged**
