### PR TITLE
feat: add versionCode parameter to promoteRelease method

### LINKED ISSUE #980: Promote specific version codes
Thanks for creating this great plugin!

### Problem description

As I understand, the `promoteArtifact` tasks will lookup all the releases in the `fromTrack` and pick the one with the highest version code to promote to the `promoteTrack`, and include any version codes in `retain.artifacts` in the lookup.

This always assumes that the latest release in the `fromTrack` is the one that should be promoted.

It should be possible to promote other releases in the `fromTrack`, assuming the version code of the release is greater than any in the `promoteTrack`.

### Potential solutions/workarounds

I'd like to request the ability to configure a specific version code for use by the `promoteArtifact` task.

If configured, the promotion task should find the release in the `fromTrack` with the configured version code(s).

The configuration could be declared as a specific version code list:
```kotlin
play {
    fromTrackVersions.add(123L) 
    // No configuration would default to the highest version code in fromTrack 
}
```

Or configured to either check the android plugin's version code, or latest from the track:
```kotlin
android {
    defaultConfig {
        versionCode = 123
    }
}

play {
    promotionMode.set(PromotionMode.CURRENT_VERSION_CODE)

    // Alternatively:
    // promotionMode.set(PromotionMode.LATEST)
    
    // No configuration would default to PromotionMode.LATEST
}
```

Either option should also be configurable from the CLI.

### Additional context

This is to support our use case where we have frequent uploads/promotions to testing tracks. We want to select specific releases to promote to production that have passed the checks of extra scrutiny. These checks can be manual and take more time than the frequency of upload to testing tracks.

I'm also happy to attempt a contribution if you agree with this approach

### PR DESCRIPTION
**Pull request by MRezaNasirloo**
Hi there!

This PR lets you specify a version code when promoting a track. Let me know if I've missed anything.

Closes #980 

```
./gradlew promoteArtifact --from-track alpha --promote-track beta --version-code 123
```

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
Seems good!

**Comment by SUPERCILEX** [comment]
Plz let me know if this works in snapshot builds.

**Comment by JamalSharif** [comment]
Dear Team, When can we expect this change to be released in next stable version?

**Comment by MRezaNasirloo** [comment]
> Plz let me know if this works in snapshot builds.

@SUPERCILEX The snapshot build has been on our project's CI for a couple of months and it's been working without an issue.

**Comment by SUPERCILEX** [comment]
Sounds good, released.

**Pull request merged**
