### PR TITLE
Add fancy logo

### LINKED ISSUE #309: Logo design contribution
Hallo 
I am Md Masud Rana 
Want to make a logo for this projects if you have any requirements then let me know.its free for any open source projects 
Thank you

### PR DESCRIPTION
**Pull request by maaudrana**
Fixes #309

### CODE REVIEW

**Comment by maaudrana** [comment]
@SUPERCILEX hey you can download svg file from <a href="https://drive.google.com/drive/folders/1HvDVZah16eIjtHnXFklKkunNqS-asNMG?usp=sharing">here</a>.can you please add this logo to readme file?

**Comment by SUPERCILEX** [comment]
@maaudrana Still looks like the SVG there has a ton of whitespace around it. I was hoping for it to be a little bit more zoomed in. If that's not possible, no problemo though it would be highly appreciated.

**Comment by maaudrana** [comment]
I am confusing actually what you want.please clear me well i will try my best.

**Comment by SUPERCILEX** [comment]
Yeah, do you see how much whitespace the logo has here?
image

I was hoping for something more zoomed in like this:
image

But in SVG form. Does that make sense?

**Comment by knordbo** [comment]
What he means is that SVGs shouldn't contain outer padding. You should have no padding as the SVG in the zip folder I've attached here. You never want to be in a situation where you need to update an asset in order to modify padding/alignment etc.

When you include it using 
``
thats when you add width height and any desired padding. Something like:
``

[logo.svg.zip](https://github.com/Triple-T/gradle-play-publisher/files/2104692/logo.svg.zip)

**Comment by SUPERCILEX** [comment]
@knordbo thanks for that! I don't have Illustrator so I was kinda stuck there. (Though I see you used sketch... either way, don't know how to use those tools so thanks.)

**Comment by bhurling** [comment]
Any reason we're not using md language?

**Comment by SUPERCILEX** [comment]
@bhurling Because we want to look fancy! ⬇️ 
image

**Comment by bhurling** [comment]
Haha. Well, then...

**Comment by bhurling** [comment]
Thanks a lot @maaudrana. That logo looks great

**Pull request merged**
