### PR TITLE
Add untrack apk task (v2)

### PR DESCRIPTION
**Pull request by bhurling**
My take on the untracking of conflicting APKs (see #146). Tests are a bit clumsy because we have to mock a lot. But now it automatically untracks conflicting versions if the flag is set.

### CODE REVIEW

**Comment by bhurling** [comment]
cc @otnateos, @danmattsson

Sorry for the amount of commits but I had to fight with travis a bit.

I am going to release a snapshot or staging version with that feature would anyone of you be willing to test it?

**Comment by danmattsson** [comment]
I'd be happy to - thanks for your effort!

**Comment by bhurling** [comment]
Great. In order to test that version you have to add the maven snapshot repo and reference `1.2.0-SNAPSHOT` of the plugin:

```groovy
buildscript {
    repositories {
        jcenter()
        maven() {
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
    }

    dependencies {
        // ...
        classpath 'com.github.triplet.gradle:play-publisher:1.2.0-SNAPSHOT'
    }
}
```

then you can add the `untrackOld` parameter in the `play` block.

Let me know if you run into trouble.

**Comment by danmattsson** [comment]
Sorry @bhurling, couldn't find the time to try it today, will give it a shot tomorrow.

**Comment by bhurling** [comment]
Released as 1.2.0-beta1. You don't need to reference the snapshot repository anymore.

**Comment by otnateos** [comment]
@bhurling, sorry didn't get your message earlier, github message slip through messages from other forums. Seems like you merge the work already, should be good. I'll have a look today

**Comment by danmattsson** [comment]
Sorry for the lack of response, found out that my "clever" solution (setting track based on product flavor) didn't work after all. Until I find another way to specify the track I'll have to release manually...

When I get the opportunity to sit down and redesign the Gradle script I'll look at this again.

**Pull request merged**
