### PR TITLE
Update title character limit to 50

### LINKED ISSUE #224: Google policy update: Title limit now 50 characters
Google have recently changed their policy RE: the character limit for the Title field. It is now 50 characters. Can this plugin please be updated to reflect this change? I know in the meantime I can toggle that check to prevent it from failing the build, but that applies to all the fields.

The current limits can be found on [this support page](https://support.google.com/googleplay/android-developer/answer/113469#details), for reference.

### PR DESCRIPTION
**Pull request by Ilaeria**
Update as per Google's current support documentation: https://support.google.com/googleplay/android-developer/answer/113469#details

Fixes #224

### CODE REVIEW

**Comment by ChristianBecker** [comment]
Thanks!

**Comment by lebzuch** [comment]
I really loved to see this in next release. When can I expect new release?

**Comment by positive-infinity** [comment]
@lebzuch +1. Me too. New release including this fix would be great. Currently, I can disable the pre-check with errorOnSizeLimit = false, however, all titles > 30 chars are cropped after uploading listings, so I have to manually change them in the Play Console for now...

**Comment by Ilaeria** [comment]
@positive-infinity Yes I found that too, unfortunately. I thought just turning off the check would solve the problem in the interim but unfortunately not. Hopefully we get a new release soon.

**Comment by positive-infinity** [comment]
@ChristianBecker Just mentioned you in this discussion as I am not sure if you get notified about comments after this issue has been closed. Cheers!

**Comment by TheRealAgentK** [comment]
A new release including this fix would be really great.

**Comment by cypressious** [comment]
Currently blocked by this issue

**Comment by bhurling** [comment]
Released in version 1.2.1-beta1

**Pull request merged**
