### PR TITLE
Support for Google Play Console Internal test track.

### PR DESCRIPTION
**Pull request by sergebeauchampGoogle**
The Google Play Console supports a new Internal test track, see:

https://support.google.com/googleplay/android-developer/answer/3131213

This is available through the API by targeting the 'internal' track.

### CODE REVIEW

**Comment by ChristianBecker** [comment]
Thanks!

**Comment by hardysim** [comment]
Is this already available in a new release of this project? How can I use it?

**Comment by ChristianBecker** [comment]
@hardysim Unfortunately it's not released yet. We should release a new version, @bhurling

**Comment by bhurling** [comment]
Released in version 1.2.1-beta1

**Pull request merged**
